list( APPEND ANTLR_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/include )
list( APPEND ANTLR_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/include/antlr )
set( ANTLR_LIBRARIES antlr )
set( ANTLR_TOOL ${CMAKE_CURRENT_LIST_DIR}/bin/antlr-3.4-complete-no-antlrv2.jar )
