if("$ENV{WXWIN}" STREQUAL "")
    message(WARNING "Failed to find wxWidgets path. Please, define environment variable WXWIN.")
endif()

add_library( wxbase STATIC IMPORTED )
if ( MSVC )
    set_property( TARGET wxbase PROPERTY IMPORTED_LOCATION_RELEASE  $ENV{WXWIN}/lib/vc_lib/wxbase30u.lib )
    set_property( TARGET wxbase PROPERTY IMPORTED_IMPLIB_RELEASE    $ENV{WXWIN}/lib/vc_lib/wxbase30u.lib )
    set_property( TARGET wxbase PROPERTY IMPORTED_LOCATION_DEBUG    $ENV{WXWIN}/lib/vc_lib/wxbase30ud.lib )
    set_property( TARGET wxbase PROPERTY IMPORTED_IMPLIB_DEBUG      $ENV{WXWIN}/lib/vc_lib/wxbase30ud.lib )
elseif( MINGW )
    set_property( TARGET wxbase PROPERTY IMPORTED_LOCATION_RELEASE  $ENV{WXWIN}/lib/gcc_lib/libwxbase30u.a )
    set_property( TARGET wxbase PROPERTY IMPORTED_IMPLIB_RELEASE    $ENV{WXWIN}/lib/gcc_lib/libwxbase30u.a )
    set_property( TARGET wxbase PROPERTY IMPORTED_LOCATION_DEBUG    $ENV{WXWIN}/lib/gcc_lib/libwxbase30ud.a )
    set_property( TARGET wxbase PROPERTY IMPORTED_IMPLIB_DEBUG      $ENV{WXWIN}/lib/gcc_lib/libwxbase30ud.a )
endif()

add_library( wxcore STATIC IMPORTED )
if ( MSVC )
    set_property( TARGET wxcore PROPERTY IMPORTED_LOCATION_RELEASE  $ENV{WXWIN}/lib/vc_lib/wxmsw30u_core.lib )
    set_property( TARGET wxcore PROPERTY IMPORTED_IMPLIB_RELEASE    $ENV{WXWIN}/lib/vc_lib/wxmsw30u_core.lib )
    set_property( TARGET wxcore PROPERTY IMPORTED_LOCATION_DEBUG    $ENV{WXWIN}/lib/vc_lib/wxmsw30ud_core.lib )
    set_property( TARGET wxcore PROPERTY IMPORTED_IMPLIB_DEBUG      $ENV{WXWIN}/lib/vc_lib/wxmsw30ud_core.lib )
elseif( MINGW )
    set_property( TARGET wxcore PROPERTY IMPORTED_LOCATION_RELEASE  $ENV{WXWIN}/lib/gcc_lib/libwxmsw30u_core.a )
    set_property( TARGET wxcore PROPERTY IMPORTED_IMPLIB_RELEASE    $ENV{WXWIN}/lib/gcc_lib/libwxmsw30u_core.a )
    set_property( TARGET wxcore PROPERTY IMPORTED_LOCATION_DEBUG    $ENV{WXWIN}/lib/gcc_lib/libwxmsw30ud_core.a )
    set_property( TARGET wxcore PROPERTY IMPORTED_IMPLIB_DEBUG      $ENV{WXWIN}/lib/gcc_lib/libwxmsw30ud_core.a )
endif()

add_library( wxpng STATIC IMPORTED )
if ( MSVC )
    set_property( TARGET wxpng PROPERTY IMPORTED_LOCATION_RELEASE   $ENV{WXWIN}/lib/vc_lib/wxpng.lib )
    set_property( TARGET wxpng PROPERTY IMPORTED_IMPLIB_RELEASE     $ENV{WXWIN}/lib/vc_lib/wxpng.lib )
    set_property( TARGET wxpng PROPERTY IMPORTED_LOCATION_DEBUG     $ENV{WXWIN}/lib/vc_lib/wxpngd.lib )
    set_property( TARGET wxpng PROPERTY IMPORTED_IMPLIB_DEBUG       $ENV{WXWIN}/lib/vc_lib/wxpngd.lib )
elseif( MINGW )
    set_property( TARGET wxpng PROPERTY IMPORTED_LOCATION_RELEASE   $ENV{WXWIN}/lib/gcc_lib/libwxpng.a )
    set_property( TARGET wxpng PROPERTY IMPORTED_IMPLIB_RELEASE     $ENV{WXWIN}/lib/gcc_lib/libwxpng.a )
    set_property( TARGET wxpng PROPERTY IMPORTED_LOCATION_DEBUG     $ENV{WXWIN}/lib/gcc_lib/libwxpngd.a )
    set_property( TARGET wxpng PROPERTY IMPORTED_IMPLIB_DEBUG       $ENV{WXWIN}/lib/gcc_lib/libwxpngd.a )
endif()

add_library( wxzlib STATIC IMPORTED )
if ( MSVC )
    set_property( TARGET wxzlib PROPERTY IMPORTED_LOCATION_RELEASE   $ENV{WXWIN}/lib/vc_lib/wxzlib.lib )
    set_property( TARGET wxzlib PROPERTY IMPORTED_IMPLIB_RELEASE     $ENV{WXWIN}/lib/vc_lib/wxzlib.lib )
    set_property( TARGET wxzlib PROPERTY IMPORTED_LOCATION_DEBUG     $ENV{WXWIN}/lib/vc_lib/wxzlibd.lib )
    set_property( TARGET wxzlib PROPERTY IMPORTED_IMPLIB_DEBUG       $ENV{WXWIN}/lib/vc_lib/wxzlibd.lib )
elseif( MINGW )
    set_property( TARGET wxzlib PROPERTY IMPORTED_LOCATION_RELEASE   $ENV{WXWIN}/lib/gcc_lib/libwxzlib.a )
    set_property( TARGET wxzlib PROPERTY IMPORTED_IMPLIB_RELEASE     $ENV{WXWIN}/lib/gcc_lib/libwxzlib.a )
    set_property( TARGET wxzlib PROPERTY IMPORTED_LOCATION_DEBUG     $ENV{WXWIN}/lib/gcc_lib/libwxzlibd.a )
    set_property( TARGET wxzlib PROPERTY IMPORTED_IMPLIB_DEBUG       $ENV{WXWIN}/lib/gcc_lib/libwxzlibd.a )
endif()

set( WXWIDGETS_LIBS wxcore wxbase wxpng wxzlib comctl32 rpcrt4 )

if ( MSVC )
    set( SETUP_H_DIR $ENV{WXWIN}/lib/vc_lib/mswu )
elseif ( MINGW )
    set( SETUP_H_DIR $ENV{WXWIN}/lib/gcc_lib/mswu )
endif()

set( WXWIDGETS_INCLUDE_DIRS $ENV{WXWIN}/include ${SETUP_H_DIR} )
