macro( package name )
    project( ${name} )
    cmake_minimum_required( VERSION 2.8 )
    set( PACKAGE_NAME ${name} )
    set( ${PACKAGE_NAME}_SOURCE_FILES )
endmacro()

function( package_config pname )
    string( TOUPPER ${pname} PACKAGE_UPPER )
    string( TOLOWER ${pname} PACKAGE_LOWER )
    set( ${PACKAGE_UPPER}_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/include PARENT_SCOPE )
    set( ${PACKAGE_UPPER}_LIBRARIES ${PACKAGE_LOWER} PARENT_SCOPE )
endfunction()

function( package_source_groups )

    math( EXPR IS_ARGC_MUL_2 "${ARGC} % 2" )
    if ( IS_ARGC_MUL_2 )
        message( SEND_ERROR "Wrong number of arguments" )
    endif()

    math( EXPR GRC "${ARGC} - 2" )
    foreach( argn RANGE 0 ${GRC} 2 )
        math( EXPR NEXT_ARGN "${argn} + 1" )
        set( GROUP ${ARGV${argn}} )
        string( REPLACE "/" "\\" GROUP ${GROUP} )
        set( SRC_FILES_MASK ${ARGV${NEXT_ARGN}} )

        file( GLOB TEMP_LIST ${SRC_FILES_MASK} )
        set( SOURCE_FILES ${SOURCE_FILES} ${TEMP_LIST} )
        source_group( "${GROUP}" FILES ${TEMP_LIST} )
    endforeach()

    set( ${PACKAGE_NAME}_SOURCE_FILES ${SOURCE_FILES} PARENT_SCOPE )

endfunction()

function( package_include_dirs )
    foreach( ARGN RANGE ${ARGC} )
        include_directories( ${ARGV${ARGN}} )
    endforeach()
endfunction()

function( package_add_library )
    string( TOLOWER ${PACKAGE_NAME} TARGET_NAME )
    add_library( ${TARGET_NAME} ${${PACKAGE_NAME}_SOURCE_FILES} )
endfunction()

function( package_dependencies )
    string( TOLOWER ${PACKAGE_NAME} TARGET_NAME )
    math( EXPR PACKC "${ARGC} - 1" )
    foreach( ARGN RANGE ${PACKC} )
        set( PACKAGE ${ARGV${ARGN}} )
        find_package( ${PACKAGE} CONFIG )
        string( TOUPPER ${PACKAGE} PACKAGE )
        target_link_libraries( ${TARGET_NAME} ${${PACKAGE}_LIBRARIES} )
        include_directories( ${${PACKAGE}_INCLUDE_DIRS} )
    endforeach()
endfunction()
